CREATE OR ALTER PROCEDURE [dbo].[SELECT_PLC_FINISH]
	@DATE_FILTER DATETIME = NULL
AS
BEGIN
	SET NOCOUNT ON;

	--temp table sp 1/2 jadi
	CREATE TABLE #PlcStatus (
		PLC_ID INT,
		MC_ID INT,
		PLANT NCHAR(10),
		LINE INT, 
		LINE_NM NCHAR(100),
		MC_DATA_NAME NCHAR(100),
		COUNTER_LIMIT VARCHAR(100),
		DATA_VALUE INT, 
		PLC_DATE DATETIME2(0),
	);
	-- JALANIN SP CTR_LIM & masukkin datanya ke temp table
	INSERT INTO #PlcStatus
	EXEC [dbo].[SP_CTR_LIM] @DATE_FILTER = @DATE_FILTER;

	-- olah menjadi tampilan dashboard
	WITH CleanedData AS (
		SELECT
			PLC_ID,
			LINE,
			LINE_NM,
			REPLACE(REPLACE(MC_DATA_NAME, ' LIMIT', ''), ' PRESET', '') AS COMPONENT_NAME, -- remove words LIMIT & PRESET 
			COUNTER_LIMIT,
			DATA_VALUE,
			PLC_DATE
		FROM #PlcStatus
	),
	GroupedData AS (
		SELECT
			PLC_ID,
			LINE,
			LINE_NM,
			COMPONENT_NAME,
			MAX(CASE WHEN COUNTER_LIMIT = 'COUNTER' THEN DATA_VALUE ELSE 0 END) AS [COUNTER],
			MAX(CASE WHEN COUNTER_LIMIT = 'LIMIT' THEN DATA_VALUE ELSE 0 END) AS [LIMIT],
			MAX(PLC_DATE) AS PLC_DATE
		FROM CleanedData
		GROUP BY PLC_ID, LINE, LINE_NM, COMPONENT_NAME
	)
	SELECT
		PLC_ID,
		LINE,
		LINE_NM,
		COMPONENT_NAME AS [MC_DATA_NAME],
		[COUNTER],
		[LIMIT],
		CASE 
			WHEN [LIMIT] > 0 AND [COUNTER] >= [LIMIT] THEN 'DANGER'
			WHEN [LIMIT] > 0 AND [COUNTER] * 100.0 / [LIMIT] >= 70 THEN 'WARNING'
			ELSE 'STANDARD'
		END AS STATUS
	FROM GroupedData
	WHERE [COUNTER] > 0 OR [LIMIT] > 0
	ORDER BY PLC_ID, LINE, COMPONENT_NAME;

	DROP TABLE #PlcStatus
END;
GO
